#!/bin/bash
set -e
### BEGIN INIT INFO
# Provides:          pandora-bootparam
# Required-Start:
# Required-Stop:        umountroot
# Should-Start:
# Should-Stop:          halt reboot
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description: Open Parrot Pandora's box and clean the RAM.
### END INIT INFO

#
# Lorenzo "EclipseSpark" Faletra <eclipse@frozenbox.org>
#         Parrot Security OS www.parrotsec.org
#                      GNU/GPL v3
#

#!/bin/bash

# Define function to clear RAM and drop caches
function bomb {
	# Notify user that the script is starting
	echo "Starting Parrot Pandora's box"
	sleep 5

	# Drop caches
	echo "Pandora is dropping caches"
	if ! echo 1024 > /proc/sys/vm/min_free_kbytes; then
		echo "Failed to drop caches. Exiting."
		exit 1
	fi
	if ! echo 3  > /proc/sys/vm/drop_caches; then
		echo "Failed to drop caches. Exiting."
		exit 1
	fi
	if ! echo 1  > /proc/sys/vm/oom_kill_allocating_task; then
		echo "Failed to drop caches. Exiting."
		exit 1
	fi
	if ! echo 1  > /proc/sys/vm/overcommit_memory; then
		echo "Failed to drop caches. Exiting."
		exit 1
	fi
	if ! echo 0  > /proc/sys/vm/oom_dump_tasks; then
		echo "Failed to drop caches. Exiting."
		exit 1
	fi

	# Clear RAM
	echo "Pandora is bombing RAM"
	if ! sdmem -fllv; then
		echo "Failed to bomb RAM. Exiting."
		exit 1
	fi
	echo "RAM bombed"

	# Notify user that the script is done
	echo "Closing Parrot Pandora's box"
}

# Ask user for confirmation before running the script
read -p "This script will clear RAM and drop caches. Are you sure you want to continue? [y/n]: " choice
case "$choice" in 
  y|Y ) bomb;;
  n|N ) echo "Script cancelled";;
  * ) echo "Invalid input. Script cancelled";;
esac

exit 0





case "$1" in
        start)
                echo "Argument '$1' is not supported, use bomb instead"
        ;;
        restart|reload|force-reload)
                echo "Error: argument '$1' is not supported, use bomb instead"
        ;;
        stop)
#        	if ! grep pandora /proc/cmdline 1> /dev/null
#        	then echo "Not opening Pandora-bootparam, not enabled from kernel line"
#        	else
#              bomb
#            fi
              bomb
        ;;
        bomb)
              bomb
        ;;
        *)
              echo "USAGE: pandora bomb"
esac
